steps:
  - label: ":llama: :windows: Upload"
    command:
      - echo llamas rock
    artifact_paths: "llamas\\*.jpg"
    agents:
      queue: lox-windows

  - wait

  - label: ":llama: :linux: Download (windows glob)"
    command:
      - buildkite-agent artifact download "llamas\\*.jpg" .
      - ls .
    agents:
      queue: lox

  - label: ":llama: :linux: Download (linux glob)"
    command:
      - buildkite-agent artifact download "llamas/*.jpg" .
      - ls .
    agents:
      queue: lox

  - label: ":llama: :linux: Upload"
    command:
      - echo llamas rock
    artifact_paths: "llamas/*.jpg"
    agents:
      queue: lox

  - wait

  - label: ":llama: :windows: Download"
    command:
      - buildkite-agent artifact download "llamas/*.jpg" .
      - dir
    agents:
      queue: lox-windows



