steps:
  - label: ":llama: :windows: Upload"
    command:
      - bash create_artifacts.sh
      - echo llamas rock
    artifact_paths: "log/*.log;client-src/integration-tests/screenshots/**/*"
    agents:
      queue: lox-windows

  - wait

  - label: ":llama: :linux: Download"
    command:
      - buildkite-agent artifact download "**/*" .
      - ls -alR .
    agents:
      queue: lox

  - label: ":llama: :linux: Upload"
    command:
      - bash create_artifacts.sh
      - echo llamas rock
    artifact_paths: "log/*.log;client-src/integration-tests/screenshots/**/*"
    agents:
      queue: lox

  - wait

  - label: ":llama: :windows: Download"
    command:
      - buildkite-agent artifact download "**/*" .
      - dir
    agents:
      queue: lox-windows



